package it.polimi.ingsw.action;

public enum ActionType {
    CONNECTION,
    JOININGPLAYER,

    ASKINGPLAYERSNUMBER,
    CHOSENPLAYERSNUMBER,

    CHATMESSAGE,
    WHOLECHAT,
    ASKINGCHAT,

    HAND,
    CHOOSEABLEACHIEVEMENTS,
    CHOSENACHIEVEMENT,

    PLACEDCARD,
    PLACINGCARD,
    PLACEDCARDERROR,
    CHOSENDRAWCARD,

    ASKINGDRAW,

    CHOOSESIDESTARTERCARD,
    CHOSENSIDESTARTERCARD
}
