package it.polimi.ingsw.action;

public enum ActionType {
    CONNECTION,
    JOININGPLAYER,

    CHATMESSAGE,
    WHOLECHAT,
    ASKINGCHAT,

    HAND,
    CHOOSEABLEACHIEVEMENTS,
    CHOSENACHIEVEMENT,
    CHOOSESIDESTARTERCARD
}
