package it.polimi.ingsw.networking.action;

public enum ActionType {
    CONNECTION,
    JOININGPLAYER,

    ASKINGPLAYERSNUMBER,
    CHOSENPLAYERSNUMBER,

    CHATMESSAGE,
    WHOLECHAT,
    ASKINGCHAT,

    HAND,
    CHOOSEABLEACHIEVEMENTS,
    CHOSENACHIEVEMENT,

    ASKINGPLACE,
    PLACEDCARD,
    PLACINGCARD,
    PLACEDCARDERROR,

    CHOSENDRAWCARD,
    CARDDRAWN,
    ASKINGDRAW,

    CHOOSESIDESTARTERCARD,
    CHOSENSIDESTARTERCARD,

    WINNERS
}
